[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
